### ISSUE TITLE
salt-minion process will not response after started 30 days

### ISSUE THREAD

**Issue by pengyao** [saltstack/salt-bin#21]
Salt Minion will not response salt-master  after started 30 days. The minion log is:

```
2020-04-02 13:35:40,240 [salt.utils.process:911 ][DEBUG   ][9011] Subprocess ProcessPayload-Job-20200402053540228184 added
2020-04-02 13:35:40,245 [salt.utils.lazy  :107 ][DEBUG   ][10218] Could not LazyLoad jinja.render: 'jinja.render' is not available.
2020-04-02 13:35:40,246 [salt.template    :236 ][ERROR   ][10218] The renderer "jinja|yaml" is not available
2020-04-02 13:35:40,246 [salt.loader      :660 ][CRITICAL][10218] The renderer jinja|yaml is unavailable, this error is often because the needed software is unavailable
2020-04-02 13:35:40,246 [salt.utils.process:767 ][ERROR   ][10218] An un-handled exception from the multiprocessing process 'ProcessPayload' was caught:
Traceback (most recent call last):
  File "/tmp/tmpqs888crd/lib/python3.6/site-packages/salt/utils/process.py", line 760, in wrapped_run_func
  File "/home/pengyao/.pyenv/versions/3.6.10/lib/python3.6/multiprocessing/process.py", line 93, in run
  File "/tmp/tmpqs888crd/lib/python3.6/site-packages/salt/minion.py", line 1607, in _target
  File "/tmp/tmpqs888crd/lib/python3.6/site-packages/salt/minion.py", line 1602, in run_func
  File "/tmp/tmpqs888crd/lib/python3.6/site-packages/salt/minion.py", line 1615, in _thread_return
  File "/tmp/tmpqs888crd/lib/python3.6/site-packages/salt/minion.py", line 454, in gen_modules
  File "/tmp/tmpqs888crd/lib/python3.6/site-packages/salt/loader.py", line 661, in render
salt.exceptions.LoaderError: The renderer jinja|yaml is unavailable, this error is often because the needed software is unavailable
2020-04-02 13:35:40,901 [salt.utils.process:920 ][DEBUG   ][9011] Subprocess ProcessPayload-Job-20200402053540228184 cleaned up
```

**Comment by pengyao** [comment]
The reason is pyinstaller default use `/tmp` as `runtime-tmpdir`. The pyinstaller runtime-tmpdir will cleaned by linux `tmpwatch`.  Change `runtime-tmpdir` to `/var/tmp` will be fine

**Comment by pengyao** [comment]
https://gitlab.com/saltstack/pop/pop-build/-/merge_requests/16

**Comment by dmurphy18** [comment]
@pengyao FYI -  it has been found that you might also need to build with --onedir switch to effectively use salt-minion. Lastly the salt-minion really needs to be built with Python 3.7 embedded to make use of PEP 538 and PEP 540 for those environments which have locale issues, namely the environment only supports locales 'C' and POSIX, as in some Container environments.  For example: pop-build -n my-salt-bin --onedir --locale-utf8

**Comment by dmurphy18** [comment]
Closing since merged in GitLab

**Comment by thatch45** [comment]
merged, we need to make sure that this option is added to build configs for salt
